# Generated by Django 5.0 on 2024-01-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_trainermodel_usermodel_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_trainer',
            field=models.BooleanField(),
        ),
    ]
