# Generated by Django 5.0 on 2024-02-10 10:17

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_is_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(max_length=30, validators=[users.models.validate_no_special_characters]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(max_length=30, validators=[users.models.validate_no_special_characters]),
        ),
    ]
