# Generated by Django 4.2.7 on 2023-11-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_phone_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
