version: '3'

services:
    web:
        build: .
        container_name: epass_app
        command: >
            bash -c "python manage.py migrate &&
                     python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./:/opt/epass
        env_file:
            .env.docker
        ports:
            - "8000:8000"
        depends_on:
            - postgresdb
            - redis
    celery:
        build: .
        command: celery -A ePass worker -l INFO
        container_name: ePass_celery
        env_file:
            .env.docker
        depends_on:
            - web
            - redis

    celery-beat:
        build: .
        command: >
            celery -A ePass beat -l INFO
        container_name: ePass_celery_beat_copy
        env_file:
            .env.docker
        volumes:
            - ./e-pass-copy:/e-pass-copy
        depends_on:
            - redis

    postgresdb:
        image: postgres:14.6-alpine
        container_name: epass_pdb
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            .env.docker
    redis:
        image: redis
        container_name: epass_redis

volumes:
    postgres_data: null