# Generated by Django 4.2.7 on 2023-12-15 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='students',
            field=models.ManyToManyField(related_name='students_trainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='trainers',
            field=models.ManyToManyField(related_name='section_trainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.groupmodel'),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.sectionmodel'),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='students',
            field=models.ManyToManyField(related_name='group_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='trainers',
            field=models.ManyToManyField(related_name='group_trainers', to=settings.AUTH_USER_MODEL),
        ),
    ]
