# Generated by Django 4.2.7 on 2023-12-14 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('section', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmodel',
            name='students',
            field=models.ManyToManyField(default=None, related_name='students_trainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='trainers',
            field=models.ManyToManyField(default=None, related_name='section_trainers', to=settings.AUTH_USER_MODEL),
        ),
    ]
