# Generated by Django 4.2.7 on 2023-12-15 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcodemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='confirmationcodemodel',
            unique_together={('user', 'code')},
        ),
    ]
