# Generated by Django 5.0.2 on 2024-02-23 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='students',
            field=models.ManyToManyField(related_name='student_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='trainers',
            field=models.ManyToManyField(related_name='trainers_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.groupmodel'),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='trainers',
            field=models.ManyToManyField(related_name='section_trainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='sections.sectionmodel'),
        ),
    ]
