# Generated by Django 4.2.7 on 2023-12-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmodel',
            old_name='sections',
            new_name='section',
        ),
    ]
