# Generated by Django 5.0 on 2024-01-03 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='students',
            field=models.ManyToManyField(related_name='student_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='trainers',
            field=models.ManyToManyField(related_name='trainer_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_own_section', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='students',
            field=models.ManyToManyField(related_name='student_section', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='trainers',
            field=models.ManyToManyField(related_name='trainer_section', to=settings.AUTH_USER_MODEL),
        ),
    ]
