# Generated by Django 5.0.2 on 2024-02-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_remove_groupmodel_type_lessonmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='duration',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='lessonmodel',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
