# Generated by Django 5.0 on 2024-01-03 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_alter_groupmodel_students_alter_groupmodel_trainers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='students',
            field=models.ManyToManyField(related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='trainers',
            field=models.ManyToManyField(related_name='trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
