# Generated by Django 5.0 on 2024-01-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_alter_sectionmodel_owner_alter_sectionmodel_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionmodel',
            name='students',
        ),
    ]
