# Generated by Django 5.0.2 on 2024-02-23 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership_passes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='to_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='membership_passes.passmodel'),
        ),
    ]
